[font]
size = 12.0

[font.normal]
family = "Hack Nerd Font"

[font.bold]
family = "Hack Nerd Font"

[font.italic]
family = "Hack Nerd Font"

[font.bold_italic]
family = "Hack Nerd Font"

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
        {key = "Key0", mods = "Control", action = "ResetFontSize"},
        {key = "Equals", mods = "Control", action = "IncreaseFontSize"},
        {key = "Minus", mods = "Control", action = "DecreaseFontSize"},
        {key = "Slash", mods = "Control", chars = "\u001f"},
]

[shell]
program = "/bin/zsh"

[window]
startup_mode = "Maximized"
opacity = 0.8
decorations = "Buttonless"

[selection]
save_to_clipboard = true

